name: Portal CI

on:
  push:
    paths:
      - 'shop-portal/**'
      - '.github/workflows/portal-ci.yml'
  pull_request:
    paths:
      - 'shop-portal/**'
      - '.github/workflows/portal-ci.yml'

concurrency:
  group: portal-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shop-portal
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'shop-portal/package-lock.json'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
